spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 7001
  servlet:
    context-path: ""

# mybatis
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml # ** 表示可多级目录

# log
#logging:
#  level:
#    root: info
#    com.dove.common: debug
#    com.tea.ppm: debug

